### ISSUE TITLE
Unexpected behavior- Optimize Graphics

### ISSUE THREAD

**Issue by jijoam** [SpringRoll/FlashToolkit#2] opened 2015-10-01 07:25 UTC
I have observed an issues while using the command - Optimize Graphics (toolkit v1.0.1-.4), though its intended to remove  unused graphic frame it seems to remove to the ones which are being used too.

On further probing, I found that it actually removes only the unwanted graphics, but jumbles the remaining frames which makes it look like the wrong frames where removed. This is leading to lot of confusion and additional effort as further manual intervention is needed to identify each frame and rearrange it appropriately. 

Please look into this issue, I have uploaded the FLA with the symbol where the issue was found.
path> http://cst-ts.excelindia.com/SharedTo/
file> testfile.zip

**Comment by ericente** [comment] 2015-10-01 19:18
I looked at the FLA, and it's not clear where the problem is. I select "Daniel_costume_torso" in the library, Run the "Optimize Graphics" command on it, and all of the unused keyframes are cleared, leaving the two frames that are being used in the exact same location as they have been. The animation still plays exactly the same, because the frame numbers have not been changed at all. I'm not sure why would need to manually rearrange the frames. Can you be more specific about the issue you are having?

**Comment by jijoam** [comment] 2015-10-05 09:26
I am including here a few screen grabs with details for better understanding.

![image](https://cloud.githubusercontent.com/assets/14106955/10277005/9c70a8f0-6b70-11e5-854a-5b9f224a0d0e.png)

![image](https://cloud.githubusercontent.com/assets/14106955/10277015/afa343ce-6b70-11e5-83cc-f3d3c0046316.png)

![image](https://cloud.githubusercontent.com/assets/14106955/10277026/c7e9bdd2-6b70-11e5-8c02-6b8432010793.png)

![image](https://cloud.githubusercontent.com/assets/14106955/10277034/d99bc67e-6b70-11e5-990b-297004b9dba8.png)

![image](https://cloud.githubusercontent.com/assets/14106955/10277043/e6358280-6b70-11e5-8aaa-569d89ac1fcd.png)

**Comment by andrewstart** [comment] 2015-10-05 20:06
This should fixed in release 1.1.5.

**Closed as completed by andrewstart** 2015-10-05 20:06 UTC
